[tool.poetry]
name = "tiny-wifi-analyzer"
version = "0.1.1"
description = "A tiny Wi-Fi analyzer for macOS"
authors = ["nolze <nolze@archlinux.us>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7"
pywebview = "~3.6"
pyobjc-core = "~8.5"
pyobjc-framework-cocoa = "~8.5"
pyobjc-framework-CoreWLAN = "~8.5"
pyobjc-framework-WebKit = "~8.5"

[tool.poetry.dev-dependencies]
pyinstaller = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
