[tool.poetry]
name = "tiny-wifi-analyzer"
version = "0.1.0"
description = "A tiny Wi-Fi analyzer for macOS"
authors = ["nolze <nolze@archlinux.us>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7"
pywebview = "~3.5"
pyobjc-core = "~7.3"
pyobjc-framework-cocoa = "~7.3"
pyobjc-framework-CoreWLAN = "~7.3"
pyobjc-framework-webkit = "~7.3"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
